### PR TITLE
Feature/refactored

### PR DESCRIPTION
**Pull request by ossentoo**

### CODE REVIEW

**Comment by ossentoo** [comment]
Refactoring and minor improvements

I've just discovered this library and think it will be very useful for us in getting started with mtn momo

@jkulubya thanks a lot.

I have one question though.  In this file, there is a hardcoded url:

https://github.com/jkulubya/mtn-momo-dotnet/blob/development/src/MtnMomo.NET/MomoConfig.cs

(line 8)

what is that required for?  Is it related to your own Momo configuration?  If so, perhaps, it should be removed?   If it is needs to be removed, what value should i as a user pass into the package to get it to work correctly?

**Comment by jkulubya** [comment]
Hi,
Sorry I've been a bit awol. Been busy with work. Let me look at this today and get back to you

JK

**Comment by jkulubya** [comment]
The url you refer to was the url for the test environment at the time. I see it's been changed to https://sandbox.momodeveloper.mtn.com/
The settings defaulted to using the test API, if no other  url was provided.

**Comment by jkulubya** [comment]
Thanks for the work. I'll take a look at other updates from their docs and try and bring it up to speed.

**Comment by ossentoo** [comment]
Sure. No problem. No rush. Please let me have some feedback. 

I have a bit more experience now in using the nuget so i understand why the azure api url is used. But I think the mtn sandbox address works as well and is better to use going forwards as it is the one used in their documents.

**Pull request merged**
